<?php

/**
 * Returns hex code of random color within parameters.
 *
 * The hex code is generated by uniformly generating random integers within a
 * radius of size $distribution around $mean independently for each RGB channel.
 * If this interval exceeds [0, 255], it is truncated accordingly beforehand.
 *
 * @param   int     $mean       Average brightness of returned color, must be
 *                              in [0, 255].
 * @param   int     $deviation  Maximum devation from the average.
 * @return  string
 */
function randomColor($mean, $deviation) {
    $lowerBound = $mean - $deviation;
    $upperBound = $mean + $deviation;
    if ($lowerBound < 0) $lowerBound = 0;
    if ($upperBound > 255) $upperBound = 255;

    $color = "#";
    for ($i = 0; $i < 3; $i++) {
        $channel = rand($lowerBound, $upperBound);
        $color .= str_pad(dechex($channel), 2, "0", STR_PAD_LEFT);
    }
    return $color;
}

?><!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Noah Doersing - HEJNOAH</title>
        <link href="http://fonts.googleapis.com/css?family=Arimo" rel="stylesheet" type="text/css">
        <style type="text/css">
            * {
                font-weight: normal;
                margin: 0;
                padding: 0;
                list-style-type: none;
                box-sizing: border-box;
            }
            body {
                font-family: Arimo, sans-serif;
                font-size: 16px;
                color: #eee;
                -webkit-font-smoothing: antialiased;
                background-color: <?php echo randomColor(30, 30); ?>;
                padding: 5em;
            }
            header {
                margin-bottom: 2em;
            }
            section {
                width: 100%;
                max-width: 48em;
            }
            h1 {
                font-size: 2em;
                margin-bottom: 1.25em;
            }
            h2 {
                font-size: inherit;
                margin-top: 1.67em;
            }
            li {
                margin-bottom: 0.5em;
            }
            a {
                color: #eee;
                text-decoration: none;
                opacity: .66;
            }
            a:hover {
                opacity: 1;
            }

            @media (max-width: 480px) {
                body {
                    padding: 2em 2em 1.5em;
                }
                header {
                    text-align: center;
                    margin-bottom: 1.33em;
                }
                h1 {
                    font-size: 1.5em;
                }
            }
        </style>
    </head>
    <body>
        <header>
            <!-- see logo.php -->
            <svg xmlns="http://www.w3.org/2000/svg" version="1.1" width="89" height="27">
                <path style="fill:#eee" d="m 0,0 0,21 5,0 0,-11 2,0 0,11 5,0 0,-15 -7,0 0,-6 -5,0 z m 28,0 0,4 5,0 0,-4 -5,0 z m 49,0 0,21 5,0 0,-11 2,0 0,11 5,0 0,-15 -7,0 0,-6 -5,0 z m -63,6 0,15 12,0 0,-4 -7,0 0,-2 7,0 0,-9 -12,0 z m 14,0 0,17 -2,0 0,4 7,0 0,-21 -5,0 z m 7,0 0,15 5,0 0,-11 2,0 0,11 5,0 0,-15 -12,0 z m 14,0 0,15 12,0 0,-15 -12,0 z m 14,0 0,4 7,0 0,2 -7,0 0,9 12,0 0,-15 -12,0 z m -44,4 2,0 0,2 -2,0 0,-2 z m 35,0 2,0 0,7 -2,0 0,-7 z m 14,5 2,0 0,2 -2,0 0,-2 z" />
            </svg>
        </header>
        <section>
            <h1>Hey there! My name is Noah Doersing, and I'm currently studying media informatics in Tübingen.</h1>
            <ul>
                <li><a href="https://twitter.com/Doersino">Twitter</a></li>
                <li><a href="https://github.com/doersino">GitHub</a></li>
                <li><a href="http://instagram.com/doersino">Instagram</a></li>
                <li><a href="http://www.youtube.com/Doersino">YouTube</a></li>
                <li><h2>Tumblr:</h2></li>
                <li><a href="http://neondust.tumblr.com/">Neon Dust</a></li>
                <li><a href="http://aufgeloest.tumblr.com/">Aufgelöst</a></li>
            </ul>
        </section>
    </body>
</html>
